### PR TITLE
Updated to Swift 3

### PR DESCRIPTION
**Pull request by lewisbar**
The App couldn't be run in Xcode anymore because of outdated syntax. Automatic syntax update didn't work. So I went through all errors manually (yes, a lot of work). I was able to remove all errors, changed some settings, and now the app seems to work properly in the simulator. Lots of warnings, though. Also, I added a lot of TODOs for things that still need attention.

### CODE REVIEW

**Comment by dasdom** [comment]
That's awesome! I'll have a look soon.

**Comment by lewisbar** [comment]
There's still so much to do. It's far from perfect. It was just a leap in the general direction. If I look at the code now, I instantly see things that I could have done better. I might put a bit more work into it when I find the time. I just wanted to open this pull request quickly as soon as it generally worked, to prevent conflict with other contributors, if that makes sense.

**Comment by lewisbar** [comment]
Okay, I went over it again. I think my part is done now.

**Comment by lewisbar** [comment]
Oh, I didn't want to say that there is nothing left to do. But I'm done for now.

**Comment by dasdom** [comment]
Looks good. I will work though the ToDos in the next days.

**Pull request merged**
